# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 10

[[main]]
  name = "Gallery"
  pageRef = "gallery"
  weight = 90
[[main]]
  name = "About Us"
  pageRef = "about"
  weight = 100

[[main]]
  identifier = "email"
  pre = "email"
  url = "mailto:contact@queeriosity01@gmail.com"
  weight = 150
[[main]]
  identifier = "instagram"
  pre = "instagram"
  url = "https://www.instagram.com/queeriosity__?utm_source=qr&igsh=Y3FzOWFsbWNoOGdz"
  weight = 200
[[main]]
  identifier = "discord"
  pre = "discord"
  url = "https://discord.gg/e2ujFdVx"
  weight = 300
[[main]]
  identifier = "spotify"
  pre = "spotify"
  url = "https://open.spotify.com/playlist/39AaYwRl3fCz8gEGzJCFp0?si=YwE-gyoRTZ-Vih_Q8dSIJw&pt=1201129a306184be93ff105a2a1b90e0&pi=ppnwoOsRQ92Fb"
  weight = 350
  
[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/AmanRathoreP/Queeriosity-Website"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20
